### ISSUE TITLE
Change Macros to Support Rust Analyzer Autocomplete

### ISSUE THREAD

**Issue by jbuckmccready** [tokio-rs/async-stream#95]
When using the `stream!` or `try_stream!` macros autocomplete with rust analyzer works fine until a `yield` statement is written, this is due to the macro no longer expanding if there is any invalid rust (but only once a `yield` statement has been written). See the rust analyzer issue here explaining in more detail how autocomplete fails when macros fail to expand (specifically for this crate's macros): https://github.com/rust-lang/rust-analyzer/issues/12759

I have no experience writing proc macros, I'm wondering is it possible to change the way the proc macros are written to always expand even if there is a `yield` statement and the Rust code is invalid? This would allow rust analyzer auto complete to function properly in all cases. I tested and noticed the tokio `select!` macro seems to consistently expand which allows autocomplete to function normally.

**Comment by taiki-e** [comment]
Does https://github.com/tokio-rs/async-stream/issues/68 's trick work?

In any case, https://github.com/tokio-rs/async-stream/pull/74 should solve this issue.

**Comment by jbuckmccready** [comment]
Parentheses as mentioned in https://github.com/tokio-rs/async-stream/issues/68 unfortunately doesn't fix the autocomplete - but good to know for formatting.
